### ISSUE TITLE
トップ画面のデザイン修正

### ISSUE THREAD

**Issue by mikageymir** [nakatsuka-k/AIPictors#10]
・メニューのデザイン修正（幅広なら常サイドメニュー表示）
・要素被ってるところ直す

ディスコードログ：
https://discord.com/channels/1069968879272595476/1071471113126817926/1095440874504208454

**Comment by nakatsuka-k** [comment]
＞・メニューのデザイン修正（幅広なら常サイドメニュー表示）
＞・要素被ってるところ直す
それぞれ対応させて頂きました。
https://twitter.com/AIPICTORS/status/1655201591732109314
