### ISSUE TITLE
認証のバックアップ機能

### ISSUE THREAD

**Issue by mikageymir** [nakatsuka-k/AIPictors#24]
Twitter連携等が行えなくなったときのバックアップ機能を実装する。

>私の機能確認不足だったら申し訳ないのですが、twitter垢がban時に、問い合わせ紐付け用のバックアップコードが、プロフィールの何処かに表示されると嬉しいです。
>
>管理人さんに問い合わせ時に、お手数をおかけしないので、楽かなと思いました。
>
>スマホゲーのバックコード見たいなイメージです。
>
>- シナリオとしては
>1, 認証に使用しているtwitter垢が、twitterでban
>2, twitter垢を再作成
>3, 管理人さんが、ユーザーからの問い合わせ時の垢紐付け情報の一つとして使用です。

ディスコードログ：
https://discord.com/channels/1069968879272595476/1069969218923139202/1101274889220001812

**Comment by nakatsuka-k** [comment]
対応いたしました。
https://twitter.com/AIPICTORS/status/1655178490231259136

**Comment by nakatsuka-k** [comment]
![image](https://user-images.githubusercontent.com/124619691/236675771-3d59b40a-2315-4ee8-869f-f94befe9f776.png)
