### ISSUE TITLE
Androidのchromeで見たときに新着等が追加で読み込まれない

### ISSUE THREAD

**Issue by mikageymir** [nakatsuka-k/AIPictors#27]
AndroidのChromeで再現する。

再現動画：
https://discord.com/channels/1069968879272595476/1069969294357692487/1101261846389989526

ディスコードログ：
https://discord.com/channels/1069968879272595476/1069969294357692487/1101176239340929064

**Comment by nakatsuka-k** [comment]
修正済みのためClose致します。
ディスコードログ：
https://discord.com/channels/1069968879272595476/1069969218923139202/1103218774104100945
