### ISSUE TITLE
作品ダイアログのOtherタブのActive表示

### ISSUE THREAD

**Issue by mikageymir** [nakatsuka-k/AIPictors#31]
作品ダイアログを表示し、Otherタブを選択した状態で、前後の作品に移動すると、
Comment/Otherの両方に青い下線が表示され、内容としてはコメント表示になります。
Otherタブのactive表示の解除が漏れているように思います。

**Comment by nakatsuka-k** [comment]
ご記載の通りダイアログ遷移時にactive表示の解除漏れがあったため
解除されるように修正致しました。
