### ISSUE TITLE
作品ダイアログのOtherタブの使用AIリンク先

### ISSUE THREAD

**Issue by mikageymir** [nakatsuka-k/AIPictors#32]
作品ダイアログのOtherタブの使用AIリンク先が、正しいリンク先になっていないようです。
作品ページでは、

https://www.aipictors.com/search/?ai=CustomModel(%E3%81%9D%E3%81%AE%E4%BB%96)

のようなリンクになっていますが、ダイアログでは

https://www.aipictors.com/search

になってしまっています。

**Comment by nakatsuka-k** [comment]
申し訳ございません。
報告ボタンのリリースと混ぜ込んで修正致します。

**Comment by nakatsuka-k** [comment]
修正させていただきました。
https://www.aipictors.com/search/?ai=CustomModel(%E3%81%9D%E3%81%AE%E4%BB%96)
