### ISSUE TITLE
マイページ表示の不具合

### ISSUE THREAD

**Issue by k1morisato** [nakatsuka-k/AIPictors#36]
<img src="https://user-images.githubusercontent.com/122097595/236633156-d676483c-6155-4e3c-8fb0-3d59f60e9109.png" width="480">
<img src="https://user-images.githubusercontent.com/122097595/236633162-6fab6ab0-50ed-4819-8e99-5d69b153a9ee.png" width="480">
ログイン前、マイページの表示は普通
ログイン後、マイページの表示が崩れる
  
- 画面最上部のメニューが表示されなくなる
- プロフィール画像等の表示エリアが狭くなる
- 公開スタンプが全件表示される
- 過去の投稿作品が一部しか表示されない（追加読み込みされない）
  
GoogleChrome（ゲストモード等も）、microsoftEdge、Firefoxで同症状発生。CTRL+F5、キャッシュ削除、Cookie削除でも同症状再発）

**Comment by nakatsuka-k** [comment]
![image](https://user-images.githubusercontent.com/124619691/236673079-45ba5cc6-59ee-4582-b381-4bfef9127688.png)
ありがとうございます。
現在は恐らく直っていると思われます。
ファイル更新中だったかもしれません。ご不便おかけし申し訳ございません。

**Comment by k1morisato** [comment]
ありがとうございます！お忙しい中すみません。
キャッシュクリアしてGoogleChrome/Edge等で確認してみたのですが…、同じ状況が継続しているようです。

追加で、気が付いた点が一点ございます。
例えば管理人さんのユーザページ　https://www.aipictors.com/user/?id=1
ですとか、他の方のページでは上記のような表示崩れは起こらないようです。謎。

ログイン後
https://www.aipictors.com/user/?id=491
https://www.aipictors.com/user/?id=swingwings
に自分のマイページを見ると状況が再現するようです。

上でも書いたように、ログアウト後に上記の自分のマイページを見ると表示は崩れないようです。ほんと謎。

**Comment by nakatsuka-k** [comment]
ご不便おかけし申し訳ございません。
調査させて頂きます。
頂いた詳細で暫定で原因が分かりましたので対応致します。

**Comment by k1morisato** [comment]
<img src="https://user-images.githubusercontent.com/122097595/236866435-b24b84f3-576b-496f-9eaa-f8a1761ae600.png" width="320">
マイページの表示不具合が解消されました！！
本当にありがとうございます。

**Comment by nakatsuka-k** [comment]
早速のご確認ありがとうございます
ご不便おかけし申し訳ございませんでした

**Comment by nakatsuka-k** [comment]
Close致します。
