### ISSUE TITLE
連続投稿に対するクールダウンタイム

### ISSUE THREAD

**Issue by mikageymir** [nakatsuka-k/AIPictors#6]
連続投稿について、クールダウンタイムを設けて、一定期間間を開ける必要があるように変更する。

・pixivは5分の間隔なので、同等くらいが良さそう
・予約投稿時についても、前後5分に他の予約があったらエラーとする

ディスコードログ：
https://discordapp.com/channels/1069968879272595476/1069969218923139202/1097462907261956176

**Comment by mikageymir** [comment]
投稿自体を拒否してしまうと、投稿者が投稿を諦めてしまう可能性があるので、
「連続投稿のため、しばらくたってから自動的に公開されます。」
のようなメッセージを出して、自動的に5分間間隔をあけた予約投稿の扱いにする。

**Comment by mikageymir** [comment]
別案：
連続投稿は、新着リストが同じ利用者の画像で占有されてしまうことが問題なので、
多すぎる投稿については新着非公開として作品登録する。
案１．前回の投稿から5分以内かつ新着公開なら、投稿は新着非公開
案２．過去1時間に2作品を新着公開で投稿していたら、投稿は新着非公開

**Comment by nakatsuka-k** [comment]
ありがとうございます。
案１．前回の投稿から5分以内かつ新着公開なら、投稿は新着非公開
で対策を施させていただきました。
