### ISSUE TITLE
ユーザによる通報機能

### ISSUE THREAD

**Issue by mikageymir** [nakatsuka-k/AIPictors#7]
利用者による通報機能。

現状ディスコードで報告いただいているものを、サイト上からできるようにするもの。

カテゴリの選択と、任意の追加コメントを記入できると良さそう。

UI案

カテゴリ：
　　□カテゴリが不適切（性的描写あり・R18・R18Gが適切に選ばれていない）
　　□修正が十分されていない
　　□その他
管理人へのコメント：
　［　　　　　　　　　　　］

ディスコードログ：
https://discord.com/channels/1069968879272595476/1069969218923139202/1096471119432790167

**Comment by nakatsuka-k** [comment]
こちら対応済みでしたのでCloseさせていただきます。
